services:
  - docker

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - sudo apt-get install -y bash

script:
  - bash build.sh

after_success:
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      docker push rubyonracetracks/rails_neutrino_5
    fi
